---
- name: Install Icinga2 on Gentoo OS family
  become: yes
  portage: package={{ item.package }} state=present
  with_items: '{{ icinga2_pkg }}'

- name: Start Icinga2
  become: yes
  service: name=icinga2
           state=started
           enabled=yes
