---
- name: Install https for apt (Ubuntu)
  become: yes
  apt: name=apt-transport-https state=present

- name: Get Icinga2 Apt Key for Debian OS family
  become: yes
  apt_key: url={{ icinga2_key }}
           state=present

- name: Get Icinga2 Apt Repos for Debian OS family
  become: yes
  apt_repository: repo='{{ item.repo }}'
                  update_cache=yes
                  state=present
  with_items: '{{ icinga2_deb_repos }}'

- name: Install Icinga2 on Debian OS family
  become: yes
  apt: pkg={{ item.package }}
       update_cache=yes
       state=latest
       install_recommends=no
  with_items: '{{ icinga2_pkg }}'

- name: Start Icinga2
  become: yes
  service: name=icinga2
           state=started
           enabled=yes
